apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ai-tap-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: ai-tap-demo
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/fklein82/tap-ai-demo.git
      ref:
        branch: main
